#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Regenerate board/gt-be98-mainline/linux/linux.config (savedefconfig format).
#
#   gen-linux-config.sh <patched linux tree> <open-ethernet tools/mainline-boot> \
#                       <cross prefix> [--check]
#
# The kernel config is "make allnoconfig" plus, in this order:
#   1. the open-ethernet fragments the tested images use (gt-be98-mlboot.config,
#      gt-be98-mlboot-s2.config, gt-be98-mlboot-pcie.config,
#      gt-be98-mlboot-pcie-all.config: stage 2 + all four PCIe cores);
#   2. linux/gt-be98-os.config (what the full userland needs);
#   3. CONFIG_CMDLINE (cmdline-s2 without ignore_loglevel, + loglevel=4 and
#      the PCIe options) and
#      CONFIG_INITRAMFS_SOURCE = ${BR_BINARIES_DIR}/gt-be98-initramfs.list
#      (post-image.sh writes the real list and relinks the Image).
# Every fragment line must survive olddefconfig (same rule as build.sh).
# The result is saved with savedefconfig, which Buildroot loads with
# olddefconfig and so reproduces the same .config.
#
# --check: build the config and compare it with the committed linux.config
# instead of overwriting it (exit 1 on a difference).
#
# Example (Buildroot output dir $O, after "make linux-patch"):
#   sh gen-linux-config.sh $O/build/linux-7.2.9 \
#      $O/build/gt-be98-open-ethernet-*/tools/mainline-boot \
#      $O/host/bin/aarch64-buildroot-linux-gnu-
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
KSRC=${1:?linux tree}
OET=${2:?open-ethernet tools/mainline-boot dir}
CROSS=${3:?cross prefix}
CHECK=${4:-}
OUT=$HERE/linux.config

T=$(mktemp -d)
trap 'rm -rf "$T"' EXIT
MK="make -s -C $KSRC O=$T ARCH=arm64 CROSS_COMPILE=$CROSS"

FRAGS="$OET/gt-be98-mlboot.config $OET/gt-be98-mlboot-s2.config \
$OET/gt-be98-mlboot-pcie.config $OET/gt-be98-mlboot-pcie-all.config \
$HERE/gt-be98-os.config"
for f in $FRAGS; do [ -f "$f" ] || { echo "missing fragment $f"; exit 1; }; done

CMDLINE=$(tr -s ' \n' '  ' < "$OET/cmdline-s2" | sed 's/ *$//')
# The OS console is quiet: cmdline-s2's ignore_loglevel (a bring-up aid)
# wrote every printk synchronously to the UART (~87 us/char at 115200),
# stalling whatever thread printed (the WiFi rx poll lost ~65 ms/s).
# loglevel=4 keeps warnings and worse on the UART for post-mortems; the
# post-codes still reach the be98pc earlycon because /init and
# gt-be98-postcode write them at KERN_CRIT ("<2>BE98PC xx").
case " $CMDLINE " in
*" ignore_loglevel "*) ;;
*) echo "cmdline-s2 has no ignore_loglevel any more: revisit this script"; exit 1 ;;
esac
CMDLINE=$(echo " $CMDLINE " | sed 's/ ignore_loglevel / /; s/^ //; s/ $//')
CMDLINE="$CMDLINE loglevel=4 pci=pcie_bus_safe pcie_aspm=off"

$MK allnoconfig >/dev/null
"$KSRC/scripts/kconfig/merge_config.sh" -m -O "$T" "$T/.config" $FRAGS >/dev/null
"$KSRC/scripts/config" --file "$T/.config" \
	--set-str CMDLINE "$CMDLINE" \
	--set-str INITRAMFS_SOURCE '${BR_BINARIES_DIR}/gt-be98-initramfs.list'
$MK olddefconfig >/dev/null

# every fragment line must have survived (the last fragment wins)
bad=0
cat $FRAGS | grep -E '^(CONFIG_[A-Z0-9_]+=|# CONFIG_[A-Z0-9_]+ is not set)' |
	awk '{ k = ($1 == "#") ? $2 : substr($0, 1, index($0, "=") - 1); v[k] = $0; o[k] = NR }
	     END { for (k in v) print o[k] "\t" v[k] }' | sort -n | cut -f2- |
	grep -v '^CONFIG_INITRAMFS_SOURCE=' | while read -r l; do
	case "$l" in
	"# "*)	sym=${l#\# }; sym=${sym%% *}
		! grep -qE "^$sym=[ym]" "$T/.config" ;;
	*)	grep -qxF "$l" "$T/.config" ;;
	esac || { echo "config: not applied: $l"; exit 1; }
done || bad=1
[ $bad = 0 ] || { echo "config fragments not fully applied"; exit 1; }

$MK savedefconfig >/dev/null
{
	echo "# GT-BE98 mainline OS kernel config (savedefconfig format)."
	echo "# GENERATED by board/gt-be98-mainline/linux/gen-linux-config.sh from"
	echo "# allnoconfig + open-ethernet tools/mainline-boot fragments (mlboot, s2,"
	echo "# pcie, pcie-all) + gt-be98-os.config. Do not edit by hand."
	echo "# Kernel $(make -s -C "$KSRC" kernelversion)."
	cat "$T/defconfig"
} > "$T/linux.config"

if [ "$CHECK" = --check ]; then
	if diff -u "$OUT" "$T/linux.config"; then
		echo "linux.config up to date"
	else
		echo "linux.config differs from the fragments: rerun without --check"
		exit 1
	fi
else
	cp "$T/linux.config" "$OUT"
	echo "wrote $OUT ($(wc -l < "$OUT") lines)"
fi
