#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# GT-BE98 mainline OS: build ml-bootfs.itb (Buildroot post-image script).
#
#  1. initramfs list: the rescue BusyBox + /init + rootfs.squashfs
#     ($BINARIES_DIR/gt-be98-initramfs.list, the kernel's
#     CONFIG_INITRAMFS_SOURCE);
#  2. relink the kernel with it (the exact Buildroot make command, captured
#     by the gt-be98-os LINUX_PRE_BUILD hook): only usr/ and vmlinux change,
#     the installed modules stay valid;
#  3. the board DT: open-ethernet tools/mainline-boot/gt-be98-mlboot.dts with
#     ML_USB (USB host + watchdog), ML_PCIE + ML_PCIE_ALL (four radios), the
#     256 MB MPM pool, and /chosen/bootargs = the forced CONFIG_CMDLINE;
#  4. ml-bootfs.itb with mkbootfs.py: the stock bootfs FIT (ATF, U-Boot,
#     vendor DTBs reused unchanged), our Image.lzo as "kernel", our DTB as
#     "fdt_mainline" for conf_lx_GT-BE98*;
#  5. size checks (README.md, "Size") and ml-bootfs.info.
set -eu

BR_CONFIG=${BR2_CONFIG:?run from Buildroot}
. "$BUILD_DIR/gt-be98-linux.env"	# LINUX_DIR, LINUX_VERSION (pre-build hook)
LOCAL_CONF=$(sed -n 's/^BR2_PACKAGE_GT_BE98_OS_LOCAL_CONF="\(.*\)"$/\1/p' "$BR_CONFIG")
STOCK_BOOTFS=
RESCUE=0
WDT_MAX=600
[ -n "$LOCAL_CONF" ] && . "$LOCAL_CONF"
SHARE=$HOST_DIR/share/gt-be98-mainline/mainline-boot
B=$BINARIES_DIR
export PATH="$HOST_DIR/bin:$HOST_DIR/sbin:$PATH"

die() { echo "post-image: $*" >&2; exit 1; }
[ -f "$B/rootfs.squashfs" ] || die "rootfs.squashfs missing (BR2_TARGET_ROOTFS_SQUASHFS)"
[ -x "$B/rescue/busybox" ] || die "rescue busybox missing (gt-be98-rescue-busybox)"
[ -f "$B/rescue/init" ] || die "rescue init missing (gt-be98-os)"
[ -f "$SHARE/mkbootfs.py" ] || die "$SHARE missing (gt-be98-open-ethernet)"
[ -n "$STOCK_BOOTFS" ] || die "STOCK_BOOTFS not set in the local configuration ($LOCAL_CONF)"
[ -f "$STOCK_BOOTFS" ] || die "STOCK_BOOTFS $STOCK_BOOTFS missing"

# ---- 1. initramfs ---------------------------------------------------------------
case "$RESCUE" in 0|1) ;; *) die "RESCUE must be 0 or 1" ;; esac
printf 'NET=usb\nWDT_MAX=%s\nRESCUE=%s\nROOTFS=/rootfs.squashfs\n' "$WDT_MAX" "$RESCUE" \
	> "$B/rescue/ml-defaults"
cat > "$B/gt-be98-initramfs.list" <<EOF
# generated by board/gt-be98-mainline/post-image.sh
dir /dev 0755 0 0
nod /dev/console 0600 0 0 c 5 1
nod /dev/null 0666 0 0 c 1 3
nod /dev/kmsg 0644 0 0 c 1 11
dir /proc 0755 0 0
dir /sys 0755 0 0
dir /tmp 1777 0 0
dir /root 0700 0 0
dir /etc 0755 0 0
dir /bin 0755 0 0
dir /sbin 0755 0 0
dir /usr 0755 0 0
dir /usr/bin 0755 0 0
dir /usr/sbin 0755 0 0
dir /mnt 0755 0 0
dir /lib 0755 0 0
file /bin/busybox $B/rescue/busybox 0755 0 0
slink /bin/sh busybox 0777 0 0
file /init $B/rescue/init 0755 0 0
file /etc/udhcpc.script $B/rescue/udhcpc.script 0755 0 0
file /etc/ml-defaults $B/rescue/ml-defaults 0644 0 0
file /rootfs.squashfs $B/rootfs.squashfs 0644 0 0
EOF

# ---- 2. relink the kernel with the initramfs ------------------------------------
echo "post-image: relinking the kernel with the rescue initramfs + rootfs.squashfs"
(
	unset MAKEFLAGS MAKEOVERRIDES MAKELEVEL MFLAGS
	sh "$BUILD_DIR/gt-be98-linux-relink.sh"
)
cp "$LINUX_DIR/arch/arm64/boot/Image" "$B/Image"

# ---- 3. device tree -------------------------------------------------------------
CMDLINE=$(sed -n 's/^CONFIG_CMDLINE="\(.*\)"$/\1/p' "$LINUX_DIR/.config")
[ -n "$CMDLINE" ] || die "no CONFIG_CMDLINE in $LINUX_DIR/.config"
grep -q '^CONFIG_CMDLINE_FORCE=y' "$LINUX_DIR/.config" || die "CONFIG_CMDLINE_FORCE off"
D=$B/dt
mkdir -p "$D"
printf '#define ML_BOOTARGS "%s"\n' "$CMDLINE" > "$D/mlboot-bootargs.h"
cpp -nostdinc -undef -D__DTS__ -DML_USB -DML_PCIE -DML_PCIE_ALL \
	-DML_MPM_SIZE=0x10000000 -x assembler-with-cpp \
	-I "$D" -I "$LINUX_DIR/arch/arm64/boot/dts/broadcom/bcmbca" \
	-I "$LINUX_DIR/scripts/dtc/include-prefixes" -I "$LINUX_DIR/include" \
	"$SHARE/gt-be98-mlboot.dts" > "$D/gt-be98-os.dts.pre"
dtc -q -I dts -O dtb -o "$B/gt-be98-os.dtb" "$D/gt-be98-os.dts.pre"
# the watchdog node the OS pets must be there
dtc -q -I dtb -O dts "$B/gt-be98-os.dtb" | grep -q 'brcm,bcm6345-wdt' ||
	die "DTB has no watchdog node"

# ---- 4. FIT ---------------------------------------------------------------------
lzop -f -c "$B/Image" > "$B/Image.lzo"
rm -rf "$B/fit"
python3 "$SHARE/mkbootfs.py" "$STOCK_BOOTFS" "$B/Image.lzo" "$B/gt-be98-os.dtb" \
	"$B/ml-bootfs.itb" "$B/fit"
dumpimage -l "$B/ml-bootfs.itb" > "$B/ml-bootfs.layout"

# ---- 5. size checks ---------------------------------------------------------------
# U-Boot (vendor 2019.07, relocated to the top of DRAM) reads the bootfs
# volume to 0x2000000 and decompresses the kernel to 0x200000; the arm64
# image_size (incl. BSS, le64 at offset 16) must end below the FIT:
# 0x2000000 - 0x200000 = 30 MiB. CONFIG_SYS_BOOTM_LEN of the shipped U-Boot
# is 64 MiB (README.md, "Size").
isz=$(od -A n -t u8 -j 16 -N 8 "$B/Image" | tr -d ' ')
ifile=$(stat -c %s "$B/Image")
fsz=$(stat -c %s "$B/ml-bootfs.itb")
ssz=$(stat -c %s "$STOCK_BOOTFS")
rsz=$(stat -c %s "$B/rootfs.squashfs")
lim=$((0x2000000 - 0x200000))
{
	echo "GT-BE98 mainline OS image"
	echo "built: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "kernel: $LINUX_VERSION"
	sed 's/^/release: /' "$TARGET_DIR/etc/gt-be98-release" 2>/dev/null || true
	echo "rootfs.squashfs: $rsz B"
	echo "Image file: $ifile B"
	echo "Image image_size (incl. BSS): $isz B (limit $lim B, margin $((lim - isz)) B)"
	echo "Image.lzo: $(stat -c %s "$B/Image.lzo") B"
	echo "ml-bootfs.itb: $fsz B (stock bootfs $ssz B, +$((fsz - ssz)) B)"
	echo "stock bootfs sha256: $(sha256sum "$STOCK_BOOTFS" | cut -d' ' -f1)"
	echo "rescue: RESCUE=$RESCUE WDT_MAX=$WDT_MAX"
	echo "cmdline: $CMDLINE"
	echo "sha256 ml-bootfs.itb: $(sha256sum "$B/ml-bootfs.itb" | cut -d' ' -f1)"
} > "$B/ml-bootfs.info"
cat "$B/ml-bootfs.info"
[ "$isz" -lt "$lim" ] || die "Image image_size $isz B >= $lim B: does not fit below the FIT"
[ "$isz" -lt $((lim - 1048576)) ] ||
	echo "post-image: WARNING: less than 1 MiB left below the 30 MiB limit"
