#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# GT-BE98 mainline OS: build the bootfs FIT (Buildroot post-image script).
#
# IMAGE=netroot (default, local configuration):
#   ml-bootfs.itb       stock FIT structure (mkbootfs.py: ATF, U-Boot, vendor
#                       DTBs unchanged) with our kernel and DTB only. The
#                       kernel's built-in initramfs holds /init + a static
#                       BusyBox; /init gets the OS from a GTBE98-ROOT USB
#                       partition or over HTTP (ROOTFS_URL), see
#                       package/gt-be98-os/src/rescue/init.
#   rootfs.squashfs     the OS, to serve at ROOTFS_URL (or copy to a USB
#   rootfs.squashfs.sha256   partition labelled GTBE98-ROOT)
#   ml-bootfs-pad30.itb the same FIT plus an unreferenced padding image,
#                       PAD_TOTAL_MB (default 30) MiB in total: a probe of
#                       the bootfs size the boot chain accepts (the kernel
#                       is the same, so post-codes c0.. prove it started)
# IMAGE=initrd: the rootfs squashfs as an unreferenced "rootfs" image of the
#   FIT, named to the kernel by /chosen/linux,initrd-start/-end (needs a boot
#   chain that loads a ~46 MB bootfs, which the box did NOT on 2026-10-08).
#
# Steps: 1. initramfs list + kernel relink (the exact Buildroot make
# command, captured by the gt-be98-os LINUX_PRE_BUILD hook); 2. DTB from
# open-ethernet tools/mainline-boot/gt-be98-mlboot.dts (ML_USB, ML_PCIE,
# ML_PCIE_ALL, 256 MB MPM, bootargs = the forced CONFIG_CMDLINE); 3. FITs;
# 4. size checks and ml-bootfs.info.
set -eu

BR_CONFIG=${BR2_CONFIG:?run from Buildroot}
. "$BUILD_DIR/gt-be98-linux.env"	# LINUX_DIR, LINUX_VERSION (pre-build hook)
LOCAL_CONF=$(sed -n 's/^BR2_PACKAGE_GT_BE98_OS_LOCAL_CONF="\(.*\)"$/\1/p' "$BR_CONFIG")
STOCK_BOOTFS=
RESCUE=0
WDT_MAX=600
IMAGE=netroot
ROOTFS_URL=
PAD_TOTAL_MB=30
NAND=off
[ -n "$LOCAL_CONF" ] && . "$LOCAL_CONF"
SHARE=$HOST_DIR/share/gt-be98-mainline/mainline-boot
HERE=$(cd "$(dirname "$0")" && pwd)
B=$BINARIES_DIR
export PATH="$HOST_DIR/bin:$HOST_DIR/sbin:$PATH"

die() { echo "post-image: $*" >&2; exit 1; }
[ -f "$B/rootfs.squashfs" ] || die "rootfs.squashfs missing (BR2_TARGET_ROOTFS_SQUASHFS)"
[ -x "$B/rescue/busybox" ] || die "rescue busybox missing (gt-be98-rescue-busybox)"
[ -f "$B/rescue/init" ] || die "rescue init missing (gt-be98-os)"
[ -f "$SHARE/mkbootfs.py" ] || die "$SHARE missing (gt-be98-open-ethernet)"
[ -n "$STOCK_BOOTFS" ] || die "STOCK_BOOTFS not set in the local configuration ($LOCAL_CONF)"
[ -f "$STOCK_BOOTFS" ] || die "STOCK_BOOTFS $STOCK_BOOTFS missing"
case "$RESCUE" in 0|1) ;; *) die "RESCUE must be 0 or 1" ;; esac
case "$IMAGE" in netroot|initrd) ;; *) die "IMAGE must be netroot or initrd" ;; esac
case "$NAND" in off|ro) ;; *) die "NAND must be off or ro (there is no write mode)" ;; esac
case "$ROOTFS_URL" in ''|http://*) ;; *) die "ROOTFS_URL: http:// only (BusyBox wget)" ;; esac
case "$ROOTFS_URL" in *[!A-Za-z0-9:/._~%+@-]*) die "ROOTFS_URL: unexpected characters" ;; esac
[ "$IMAGE" = netroot ] && [ -z "$ROOTFS_URL" ] &&
	echo "post-image: WARNING: IMAGE=netroot without ROOTFS_URL: only a GTBE98-ROOT USB root can boot"

# ---- 1. initramfs + kernel relink ---------------------------------------------------
{
	printf 'WDT_MAX=%s\nRESCUE=%s\n' "$WDT_MAX" "$RESCUE"
	printf 'ROOTFS_URL=%s\n' "$ROOTFS_URL"
} > "$B/rescue/ml-defaults"
cat > "$B/gt-be98-initramfs.list" <<EOF
# generated by board/gt-be98-mainline/post-image.sh
dir /dev 0755 0 0
nod /dev/console 0600 0 0 c 5 1
nod /dev/null 0666 0 0 c 1 3
nod /dev/kmsg 0644 0 0 c 1 11
dir /proc 0755 0 0
dir /sys 0755 0 0
dir /tmp 1777 0 0
dir /root 0700 0 0
dir /etc 0755 0 0
dir /bin 0755 0 0
dir /sbin 0755 0 0
dir /usr 0755 0 0
dir /usr/bin 0755 0 0
dir /usr/sbin 0755 0 0
dir /mnt 0755 0 0
dir /lib 0755 0 0
file /bin/busybox $B/rescue/busybox 0755 0 0
slink /bin/sh busybox 0777 0 0
file /init $B/rescue/init 0755 0 0
file /etc/udhcpc.script $B/rescue/udhcpc.script 0755 0 0
file /etc/ml-defaults $B/rescue/ml-defaults 0644 0 0
EOF
echo "post-image: relinking the kernel with the rescue initramfs"
(
	unset MAKEFLAGS MAKEOVERRIDES MAKELEVEL MFLAGS
	sh "$BUILD_DIR/gt-be98-linux-relink.sh"
)
cp "$LINUX_DIR/arch/arm64/boot/Image" "$B/Image"
lzop -f -c "$B/Image" > "$B/Image.lzo"

# the rootfs for HTTP / USB
(cd "$B" && sha256sum rootfs.squashfs > rootfs.squashfs.sha256)

# ---- 2. device tree ---------------------------------------------------------------
FIT_LOAD=0x2000000
CMDLINE=$(sed -n 's/^CONFIG_CMDLINE="\(.*\)"$/\1/p' "$LINUX_DIR/.config")
[ -n "$CMDLINE" ] || die "no CONFIG_CMDLINE in $LINUX_DIR/.config"
grep -q '^CONFIG_CMDLINE_FORCE=y' "$LINUX_DIR/.config" || die "CONFIG_CMDLINE_FORCE off"
D=$B/dt
mkdir -p "$D"
printf '#define ML_BOOTARGS "%s"\n' "$CMDLINE" > "$D/mlboot-bootargs.h"
cat > "$D/gt-be98-os.dts" <<'EOF'
/* GT-BE98 mainline OS: the diagnostic board dts (+ the rootfs initrd) */
#include "gt-be98-mlboot.dts"

/*
 * NAND=ro (PHASE 1, read-only): the BCM4916 NAND controller (mainline
 * bcm6813.dtsi nand-controller@1800, bcmbca glue). ECC strength, step size
 * and spare area come from the boot straps, as the stock driver does
 * (brcm,nand-ecc-use-strap: read back from ACC_CONTROL, programmed by the
 * boot ROM / loader). On-flash BBT as stock. Partitions as stock's
 * mtdparts=brcmnand.0:2097152(loader),265289728@2097152(image), both
 * read-only: no MTD_WRITEABLE, UBI attaches in read-only mode; the kernel
 * patch 0001 (board/gt-be98-mainline/patches/linux) makes brcmnand refuse
 * program/erase without brcmnand.allow_write=1 on top of that.
 */
#ifdef ML_NAND_RO
&nand_controller {
	status = "okay";
};

&nandcs {
	nand-on-flash-bbt;
	brcm,nand-ecc-use-strap;

	partitions {
		compatible = "fixed-partitions";
		#address-cells = <1>;
		#size-cells = <1>;

		partition@0 {
			label = "loader";
			reg = <0x0 0x200000>;
			read-only;
		};

		partition@200000 {
			label = "image";
			reg = <0x200000 0xfd00000>;
			read-only;
		};
	};
};
#endif

#ifdef ML_INITRD_START
/ {
	chosen {
		linux,initrd-start = /bits/ 64 <ML_INITRD_START>;
		linux,initrd-end = /bits/ 64 <ML_INITRD_END>;
	};
};
#endif
EOF
mkdtb() {	# [initrd start, initrd end]
	set -- ${1:+-DML_INITRD_START=$1 -DML_INITRD_END=$2}
	[ "$NAND" = ro ] && set -- "$@" -DML_NAND_RO
	cpp -nostdinc -undef -D__DTS__ -DML_USB -DML_PCIE -DML_PCIE_ALL \
		-DML_MPM_SIZE=0x10000000 "$@" -x assembler-with-cpp \
		-I "$D" -I "$SHARE" -I "$LINUX_DIR/arch/arm64/boot/dts/broadcom/bcmbca" \
		-I "$LINUX_DIR/scripts/dtc/include-prefixes" -I "$LINUX_DIR/include" \
		"$D/gt-be98-os.dts" > "$D/gt-be98-os.dts.pre"
	dtc -q -I dts -O dtb -o "$B/gt-be98-os.dtb" "$D/gt-be98-os.dts.pre"
}

# ---- 3. FITs ------------------------------------------------------------------------
BASE=$(python3 "$HERE/fit-rootfs.py" base "$STOCK_BOOTFS")
# $1 out.itb, then optional extra images: name file type ...
mkfit() {
	out=$1; shift
	rm -rf "$B/fit"
	python3 "$SHARE/mkbootfs.py" "$STOCK_BOOTFS" "$B/Image.lzo" "$B/gt-be98-os.dtb" \
		"$out" "$B/fit" >/dev/null
	its=$B/fit/bootfs.its
	n=0
	while [ $# -ge 3 ]; do
		n=$((n + 1))
		python3 "$HERE/fit-rootfs.py" add "$its" "$2" "$B/fit/extra$n.its" "$1" "$3"
		its=$B/fit/extra$n.its
		shift 3
	done
	[ $n = 0 ] || mkimage -E -p "$BASE" -f "$its" "$out" >/dev/null
}

rm -f "$B/ml-bootfs.itb" "$B/ml-bootfs-pad30.itb" "$B/ml-bootfs-pad"*.itb
if [ "$IMAGE" = netroot ]; then
	mkdtb
	mkfit "$B/ml-bootfs.itb"
	# size probe: same FIT + padding up to PAD_TOTAL_MB MiB
	base=$(stat -c %s "$B/ml-bootfs.itb")
	padsz=$((PAD_TOTAL_MB * 1048576 - base - 4096))
	[ "$padsz" -gt 0 ] || die "PAD_TOTAL_MB=$PAD_TOTAL_MB is below the FIT size"
	head -c "$padsz" /dev/urandom > "$B/pad.bin"
	mkfit "$B/ml-bootfs-pad$PAD_TOTAL_MB.itb" pad "$B/pad.bin" firmware
	rm -f "$B/pad.bin"
else
	printf 'file /rootfs.squashfs %s 0644 0 0\n' "$B/rootfs.squashfs" > "$B/rootfs.cpio.list"
	"$LINUX_DIR/usr/gen_init_cpio" "$B/rootfs.cpio.list" > "$B/rootfs.cpio"
	# pass 1: placeholder addresses (64-bit cells: same DTB size)
	mkdtb 0x0 0x0
	mkfit "$B/ml-bootfs.itb" rootfs "$B/rootfs.cpio" ramdisk
	set -- $(python3 "$HERE/fit-rootfs.py" pos "$B/ml-bootfs.itb" rootfs)
	POS=$1 LEN=$2
	START=$(printf '0x%x' $((FIT_LOAD + POS)))
	END=$(printf '0x%x' $((FIT_LOAD + POS + LEN)))
	# pass 2: the real addresses; the layout must not move
	mkdtb "$START" "$END"
	mkfit "$B/ml-bootfs.itb" rootfs "$B/rootfs.cpio" ramdisk
	set -- $(python3 "$HERE/fit-rootfs.py" pos "$B/ml-bootfs.itb" rootfs)
	[ "$1 $2" = "$POS $LEN" ] || die "FIT layout moved between the passes"
	magic=$(dd if="$B/ml-bootfs.itb" bs=1 skip="$POS" count=6 2>/dev/null)
	[ "$magic" = 070701 ] || die "no newc cpio at FIT offset $POS"
fi
dumpimage -l "$B/ml-bootfs.itb" > "$B/ml-bootfs.layout"
dtc -q -I dtb -O dts "$B/gt-be98-os.dtb" > "$D/gt-be98-os.dtb.dts"
grep -q 'brcm,bcm6345-wdt' "$D/gt-be98-os.dtb.dts" || die "DTB has no watchdog node"
if [ "$NAND" = ro ]; then
	# every NAND partition must be read-only
	awk '/partition@/{p=1; ro=0} p&&/read-only/{ro=1} p&&/^\t*};/{if(!ro){print "rw"; exit} p=0}' \
		"$D/gt-be98-os.dtb.dts" | grep -q rw && die "a NAND partition is not read-only"
	grep -q 'brcm,nand-ecc-use-strap' "$D/gt-be98-os.dtb.dts" || die "NAND node missing"
fi

# minimal squashfs for slot 1's rootfs volume (vol 4): U-Boot only checks
# its squashfs magic before booting slot 1 (README.md, "Flash space")
rm -rf "$B/rootfs1-stub.d" "$B/rootfs1-stub.squashfs"
mkdir -p "$B/rootfs1-stub.d"
echo "GT-BE98 mainline OS: slot 1 rootfs placeholder (the OS is elsewhere)" \
	> "$B/rootfs1-stub.d/README"
mksquashfs "$B/rootfs1-stub.d" "$B/rootfs1-stub.squashfs" -noappend -all-root \
	-mkfs-time 0 -all-time 0 -no-progress >/dev/null

# ---- 4. size checks ---------------------------------------------------------------
# README.md, "Size limits": the kernel (image_size incl. BSS, le64 at
# offset 16) must end below the FIT at 0x2000000; the bootfs itself: the
# 14.7 MB diagnostic images boot, a 46 MB one did not reach the kernel
# (2026-10-08), so the netroot FIT stays under 16 MiB.
isz=$(od -A n -t u8 -j 16 -N 8 "$B/Image" | tr -d ' ')
lim=$((0x2000000 - 0x200000))
fsz=$(stat -c %s "$B/ml-bootfs.itb")
ssz=$(stat -c %s "$STOCK_BOOTFS")
sha() { sha256sum "$1" | cut -d' ' -f1; }
{
	echo "GT-BE98 mainline OS image (IMAGE=$IMAGE)"
	echo "built: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "kernel: $LINUX_VERSION"
	sed 's/^/release: /' "$TARGET_DIR/etc/gt-be98-release" 2>/dev/null || true
	echo "Image file: $(stat -c %s "$B/Image") B, image_size (incl. BSS) $isz B (limit $lim B)"
	echo "Image.lzo: $(stat -c %s "$B/Image.lzo") B"
	echo "ml-bootfs.itb: $fsz B (stock bootfs $ssz B) sha256 $(sha "$B/ml-bootfs.itb")"
	[ ! -f "$B/ml-bootfs-pad$PAD_TOTAL_MB.itb" ] ||
		echo "ml-bootfs-pad$PAD_TOTAL_MB.itb: $(stat -c %s "$B/ml-bootfs-pad$PAD_TOTAL_MB.itb") B sha256 $(sha "$B/ml-bootfs-pad$PAD_TOTAL_MB.itb")"
	echo "rootfs.squashfs: $(stat -c %s "$B/rootfs.squashfs") B sha256 $(sha "$B/rootfs.squashfs")"
	[ "$IMAGE" = netroot ] || echo "rootfs initrd in RAM: $START..$END"
	echo "rootfs1-stub.squashfs: $(stat -c %s "$B/rootfs1-stub.squashfs") B sha256 $(sha "$B/rootfs1-stub.squashfs")"
	echo "stock bootfs sha256: $(sha "$STOCK_BOOTFS")"
	echo "boot: RESCUE=$RESCUE WDT_MAX=$WDT_MAX ROOTFS_URL=${ROOTFS_URL:-<none>} NAND=$NAND"
	echo "cmdline: $CMDLINE"
} > "$B/ml-bootfs.info"
cat "$B/ml-bootfs.info"
[ "$isz" -lt "$lim" ] || die "Image image_size $isz B >= $lim B: does not fit below the FIT"
if [ "$IMAGE" = netroot ]; then
	[ "$fsz" -le $((16 * 1048576)) ] || die "netroot FIT $fsz B > 16 MiB"
fi
exit 0
